morph_tool/converter.py

* https://github.com/neuronsimulator/nrn/blob/636e75c0c4b6eb7b97597b8224081e59183ee1c9/share/lib/hoc/import3d/import3d_gui.hoc#L1195
* Props to @asanin-epfl for tracking this down
* fixes #6

Missing normalization in contour2centroid, compared to NEURON

---

README.rst
morph_tool/cli.py
morph_tool/converter.py
tests/test_converter.py

- formats that use a contour can be converted to have a spherical soma in SWC, as the SONATA spec requires.

allow for creation of single point SWC somas for SONATA spec

---

morph_tool/nrnhines.py
tests/test_loader.py
tests/test_nrnhines.py
tests/test_transform.py

This is a proposal PR to allow for converting a list of 3d points to a list of neuron isections with multiprocessing. This can be used to process a large number of morphologies, and requires each computation to be isolated to prevent NEURON clashes with itself.
Things to do/discuss:
- is this the correct place?
- shall we add an app?
- it needs some tests
- it may assume too much from the file structure, etc... for a generic user
- the isolating functions should be used for any NEURON based computations in parallel, so it may serve for other functions in the package. It may be worth moving these (along with NestedPool) to a utils.py?

multiple point to isec converter

---

morph_tool/cli.py
morph_tool/converter.py
morph_tool/dendrogram.py
morph_tool/loader.py
tests/test_loader.py

This is to allow for a complete bypassing of lru_cache from outside (in particular, placement-algorithm without mpi)

bypassing lru_cache if cache_size=0 in MorphLoader

---

morph_tool/graft.py
morph_tool/utils.py
tests/data/neurondb-no-repair.xml
tests/test_utils.py

When reading an XML neurondb, use_axon will default to True
if the <repair> tag is missing.
Cf the famous quote:
"According to Eilif, an empty use_axon (corresponding to a null in the database)
means that the axon is supposed to be used"

Update neurondb_dataframe to handle empty <repair> tag

---

morph_tool/transform.py

'scipy.spatial.transform.rotation.Rotation' object has no attribute 'as_dcm'
'as_dcm' is actually the same as 'as_matrix'
https://docs.scipy.org/doc/scipy-1.4.0/reference/generated/scipy.spatial.transform.Rotation.as_dcm.html

Fix scipy breaking change in 1.6.0

---

morph_tool/cli.py
morph_tool/morphio_diff.py
tests/test_diff.py

to change the tolerances.
See https://numpy.org/doc/stable/reference/generated/numpy.allclose.html
When two morphologies differ, it will report which index of the vector differs
and the values that differ.
```
$ morph-tool diff actual.h5 expected.h5 --rtol 0.1
INFO:morph_tool:Morphologies not identical
INFO:morph_tool:Attributes Section.diameters of:
Section(id=0, points=[(-5.006 -1.56494 -1.50834),..., (-17.1488 -8.69046 -6.10697)])
Section(id=0, points=[(-5.006 -1.56494 -1.50834),..., (-17.1488 -8.69046 -6.10697)])
have the same shape but different values
Vector diameters differs at index 1: 0.8771874904632568 != 0.48936277627944946
```

📝 Improve morph-tool diff

---

morph_tool/converter.py
setup.py

The output of `morphio.Morphology.version` has changed in v2.7.0. This commits makes morph-tool compatible with the new output format.

Use new signature for morphio.Morphology.version

---

morph_tool/morphdb.py
tests/test_morphdb.py

MorphDB.df is currently not hashable because of the column `axon_input` which is a list. And lists are not hashable.
Change `axon_input` column to a tuple to make the dataframe hashable
Fixes #52

Make MorphDB.df hashable

---

morph_tool/resampling.py
tests/test_resampling.py

@arnaudon encountered an issue when resampling neuronal morphologies where the two last resampled points were identical.
This was due to the numerical imprecision of the cumulative values in `np.arange(dl, total_length, dl)`. In some cases, due to the numerical error of the summation, the value `total_length` was returned at the end of the array.
To fix this the arrange is converted to `np.arange(1, n_segments) * dl` to avoid such errors and ensure that the correct size is always created.

Fix resampling duplicate point because of numerical imprecision

---

morph_tool/morphio_diff.py
morph_tool/nrnhines.py
tests/data/morphdb/from_neurondb/features.csv
tests/test_diff.py
tox.ini

NestedPool fails for Py38
Force the ``group`` argument to None in the constructor of ``NestedPool.Process``.

Fix NestedPool for py38

---

morph_tool/__init__.py
morph_tool/axon_point.py
morph_tool/morphdb.py
morph_tool/resampling.py
tests/test_axon_point.py

Similar to apical point detection, having an axon point detection is useful. The axon point is defined as the terminal of the main axon, only for PC axons. A PC axon has a main thick branch from the soma going donwards, from which smaller branches emerge. For electrical models and correct axon diametrizations, detecting which branch is the main axon is crucial.
We propose an algorithm with @mzbili in this PR.

Introduce axon point module

---

morph_tool/graft.py

In region-grower we use Numpy random generator objects instead of the global numpy.random. We need to pass these objects to graft_axon as there is a random generation in grafting_position.
This PR adds new parameters to allow to pass a random number generator. If nothing is passed, numpy.random is used, so it is not a breaking change.

Allow to pass numpy rangom generators to graft_axon

---

morph_tool/graft.py
tests/test_graft.py

Numpy 1.21 changed the signature of `np.random.Generator.uniform`.
Use kwargs for `rng.random.uniform`.

Fix compatibility with numpy>=1.21

---

CHANGELOG.rst
morph_tool/spatial.py
tests/test_spatial.py

In one instance, this failed as strict equalities were not working with rounding errors.
np.isclose solves it

use isclose in spatial

---

morph_tool/converter.py
morph_tool/nrnhines.py
morph_tool/plot/dendrogram.py
morph_tool/transform.py
tox.ini

Fixes error due to the adding of the group as an index to the jittered dataframe.
```python
E       ValueError: operands could not be broadcast together with shapes (5,2) (3,) (5,2)
```

Fix dendrogram jittered dataframe not include group index

---

morph_tool/converter.py
tox.ini

This PR depends on #122 
*.h5 file should also convert `SOMA_SINGLE_POINT` into `SOMA_SIMPLE_CONTOUR` (required by `MorphIO==3.3.7`). 
Call `single_point_sphere_to_circular_contour()` also for h5 files.

Fix converter.from_swc

---

morph_tool/converter.py
tests/test_converter.py

The converter creates soma with `nan` when the first and last point are equal in SOMA_CYLINDERS case.
We iterate over the points of the soma until we find one that is different from the first one.
If we can't find one we raise an exception.

Fix equal point in SOMA_CYLINDERS in SWC converter

---

morph_tool/cli.py
morph_tool/converter.py
setup.py
tests/test_converter.py

For emodel, if we convert swc to asc, neuron does not read the same soma surface area, hence the model behave differently.
It is quite hard to find a correction factor from asc loader (swc is just area = 4 *pi * R^2), hence we do a simple optimisation.

Feat: Ensure area is same as nrn for point swc soma

---

morph_tool/morphio_diff.py
tests/test_diff.py

The `morph_tool.morphio_diff.diff()` function returns only the first difference found between the 2 given morphologies. In some cases it can be more convenient to get all errors at once.
Collect all errors and create a `DiffResult` object that joins all error descriptions.

Can get all differences between 2 morphs instead of only the first one

---

morph_tool/morphdb.py
tests/test_morphdb.py

In previous versions of this API (which never made it to github, but still in gitlab morphology-processing-workflow), this was the case, and it makes sense to have it for cleaner processing later.
Just using pandas

Feat: Drop morphdb duplicates in __add__
